apiVersion: v1
kind: ConfigMap       
metadata:
  name: prometheus-server-conf
  namespace: team4project3

data:
  prometheus.yml: |
    global:
      scrape_interval: 15s  
      evaluation_interval: 15s  

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'backend-metrics'
        static_configs:
          - targets: ['catus-locatus-svc:4001']
        metrics_path: /api/metrics
        scrape_interval: 10s