frontend:
  - patterns:
      - frontend/**

backend:
  - patterns:
      - backend/**

infrastructure-aws:
  - patterns:
      - terraform/aws/**

infrastructure-azure:
  - patterns:
      - terraform/azure/**

infrastructure-k8s:
  - patterns:
      - terraform/k8s/**

kubernetes:
  - patterns:
      - k8s/**

ci/cd:
  - patterns:
      - .github/workflows/**

documentation:
  - patterns:
      - "**/*.md"
      - docs/**
