kind: Deployment
apiVersion: apps/v1
metadata:
  name: frontend-deployment
  namespace: 
  labels:
    app: frontend
    tier: frontend
    version: v1.0
  #annotations for prometehus here

  
    
spec:
  replicas: 3
  selector:
    matchLabels:
      app: frontend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template: 
    metadata:
      labels:
        app: frontend
        tier: frontend
        version: v1.0
    spec:
      containers:
        - name: frontend
          image: nginx:latest
          ports:
            - containerPort: 80
              protocol: TCP
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
            envFrom:
              - configMapRef:
                  name: frontend-config
              - secretRef:
                  name: frontend-secret      
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          readinessProbe: 
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5