apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app-ingress
  labels:
    app: three-tier-app
spec:
  tls:
  - hosts:
    - https-alialjaffer.com
    secretName: tls-secret
  rules:
  - host: https-alialjaffer.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: cl-fe-svc
            port:
              number: 80
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: catus-locatus-svc
            port:
              number: 4001