name: Backend CI/CD

on:
  workflow_call:

permissions:
  id-token: write
  contents: read

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      - name: Login to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Log in to ACR
        run: az acr login --name ${{ vars.ACR_NAME }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: true
          context: ./backend
          tags: |
            ${{ vars.ACR_NAME }}.azurecr.io/backend-t4p3:latest
            ${{ vars.ACR_NAME }}.azurecr.io/backend-t4p3:${{ github.sha }}